# Generated by Django 5.2 on 2025-07-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='artista',
            field=models.CharField(default='Artista Desconocido', max_length=100),
            preserve_default=False,
        ),
    ]
