# Generated by Django 5.2 on 2025-07-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_artista'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora',
            field=models.CharField(default='por definir', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(),
        ),
    ]
